/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete your account
         * @description Deletes everything Pebble stores about you, in every table, for good. Signing in again starts afresh.
         */
        delete: operations["delete_account_api_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download all your data
         * @description Everything Pebble stores about you, as one JSON file: every row of every table that belongs to you
         *     (tasks, their steps, preferences, the activity log). Uploaded documents are never stored, so they
         *     aren't in it.
         */
        get: operations["export_account_data_api_account_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your activity log
         * @description What each agent did for you and why, newest first. The agents write their own entries.
         */
        get: operations["list_activity_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with Pebble
         * @description **Pebble Orchestrator** — The main entry point for talking to Pebble.
         *
         *     Classifies the user's intent and routes to the appropriate sub-agent:
         *     - `decompose` → CalmSense (task breakdown)
         *     - `simplify` → SimplifyCore (text simplification)
         *     - `motivate` → PebbleVoice (encouragement)
         *     - `chat` → Direct response from Pebble
         *     - `distress` → Immediate empathetic response with support
         *
         *     All input is screened by Prompt Shields (anti-jailbreak) and Content Safety, then PII-redacted:
         *     the classifier and every sub-agent see only the redacted message. A flagged reply is replaced
         *     with a safe one.
         *
         *     If the user expresses distress (*"I'm overwhelmed"*, *"I can't do this"*),
         *     Pebble responds with empathy and offers to simplify their day.
         *
         *     The `data` field contains structured output from the sub-agent (e.g., steps
         *     for decompose, simplified text for simplify), or `null` for chat/distress.
         */
        post: operations["chat_api_agents_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/decompose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Break down a task
         * @description **Agent: CalmSense** — Takes a task title and breaks it into smaller, achievable steps.
         *
         *     Respects the user's preferred step size:
         *     - `small`: 5-10 minute steps
         *     - `medium`: 15-20 minute steps
         *     - `large`: 30+ minute steps
         *
         *     The agent starts with the easiest step to reduce task initiation friction,
         *     and includes a `whyExplanation` describing why it chose this breakdown.
         *
         *     Input and output go through the safety gate (Content Safety and PII redaction).
         */
        post: operations["decompose_api_agents_decompose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/motivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get encouragement
         * @description **Agent: PebbleVoice** — Generates specific, personalized encouragement.
         *
         *     Never generic platitudes. The agent references the user's actual progress:
         *     - *"You finished reading that chapter even though you said it felt hard"*
         *     - *"Starting is the hardest part, and you did that"*
         *
         *     Returns a `mood` that the frontend uses to update Pebble's expression:
         *     `sleepy`, `normal`, `happy`, or `excited`.
         */
        post: operations["motivate_api_agents_motivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/simplify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simplify text
         * @description **Agent: SimplifyCore** — Simplifies complex text to a target reading level (1-10).
         *
         *     Reading level scale:
         *     - **1-3**: Very short sentences, common words only
         *     - **4-6**: Clear language, some compound sentences
         *     - **7-9**: Closer to original, simplified structure
         *     - **10**: Minimal changes, just improved clarity
         *
         *     Also extracts action items (`extractedTasks`) and topic tags from the text.
         *     Includes a `whyExplanation` describing what was changed and why.
         *     Output is verified against the original text using Groundedness Detection.
         */
        post: operations["simplify_api_agents_simplify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/immersive-reader/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an Immersive Reader token
         * @description A short-lived token for Microsoft's Immersive Reader, used by the frontend's `launchAsync`.
         *
         *     Optional: without `IMMERSIVE_READER_*` settings this is a 503, and the frontend uses its built-in reader.
         */
        get: operations["immersive_reader_token_api_documents_immersive_reader_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read a document's text
         * @description Read the text of an uploaded document with a local parser (pypdf, python-docx).
         *
         *     The file is parsed in memory and **never stored**: nothing is written to disk or sent to
         *     another service. Pass the returned `text` to `POST /api/agents/simplify` to simplify it.
         */
        post: operations["parse_api_documents_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if the server is running.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import what this browser kept
         * @description Moves tasks, preferences and activity entries that the browser kept before sign-in into your account.
         *     The frontend sends them once and then forgets its copy.
         *
         *     - Tasks are added after yours, with their steps.
         *     - Preferences apply only if you never saved any.
         *     - Log entries keep their times (none later than now).
         */
        post: operations["import_local_data_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your preferences
         * @description Your saved preferences over the defaults. A new account gets the defaults.
         */
        get: operations["get_preferences__api_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change some preferences
         * @description Change only the fields you send, for example `{"calmMode": true}`. Returns all of them.
         */
        patch: operations["update_preferences_api_preferences_patch"];
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your progress
         * @description What you finished: tasks, steps and focus minutes over the last `days` days (in your time zone), tasks per
         *     tag, one entry per day, and all-time totals. Counts only ever add up: unticking or deleting a task later
         *     doesn't take back that you finished it. Nothing goes back to zero, and there are no goals or comparisons.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Note a focus session
         * @description A focus session is over: its minutes count towards your progress.
         */
        post: operations["add_focus_session_api_stats_focus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your tasks
         * @description Your tasks in the order you added them, each with its steps.
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /**
         * Add a task
         * @description Add a task to the end of your list. Pebble picks the ids of the task and its steps.
         */
        post: operations["add_task_api_tasks_post"];
        /**
         * Clear your list
         * @description Remove every task on your list.
         */
        delete: operations["clear_tasks_api_tasks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder your list
         * @description Put your tasks in this order. List every task exactly once; if the list changed meanwhile (or an id
         *     isn't yours), nothing moves and the answer is 409.
         */
        put: operations["reorder_tasks_api_tasks_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a task */
        delete: operations["delete_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Change a task
         * @description Change only the fields you send, for example `{"completed": true}`.
         */
        patch: operations["update_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Break a task down with CalmSense
         * @description CalmSense splits the task into steps of your step size and says why; they replace its steps.
         *
         *     The title is safety-checked first (422 if it's held back). If CalmSense can't answer, it's a 503 and the
         *     task stays as it was. The result goes in your activity log.
         */
        post: operations["break_down_api_tasks__task_id__breakdown_post"];
        /**
         * Remove a task's breakdown
         * @description Undo or dismiss a CalmSense breakdown: the task keeps its title, tag and the rest, without steps or "why".
         *
         *     Progress already made isn't taken back (counts only add up).
         */
        delete: operations["remove_breakdown_api_tasks__task_id__breakdown_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a task's steps
         * @description Set a task's steps, for example from a CalmSense breakdown. The new steps start open.
         */
        put: operations["replace_steps_api_tasks__task_id__steps_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Tick a step on or off
         * @description Finishing the last open step also finishes the task. Unticking a step never reopens it.
         */
        patch: operations["update_step_api_tasks__task_id__steps__step_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEntryOut */
        ActivityEntryOut: {
            /** Action */
            action: string;
            agent: components["schemas"]["AgentName"];
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Id */
            id: string;
            /** Reasoning */
            reasoning: string;
            safetyStatus: components["schemas"]["SafetyStatus"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * AgentName
         * @enum {string}
         */
        AgentName: "CalmSense" | "SimplifyCore" | "PebbleVoice" | "AdaptLens" | "WhyBot" | "BridgeBot";
        /** Body_parse_api_documents_parse_post */
        Body_parse_api_documents_parse_post: {
            /**
             * File
             * @description PDF, Word (.docx) or plain-text file. Max 10 MB.
             */
            file: string;
        };
        /** BreakdownRequest */
        BreakdownRequest: {
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** ByTagOut */
        ByTagOut: {
            /** Communication */
            communication: number;
            /** Project */
            project: number;
            /** Study */
            study: number;
            /** Wellbeing */
            wellbeing: number;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Personality
             * @default gentle
             */
            personality: string;
            /**
             * Readinglevel
             * @default 5
             */
            readingLevel: number;
            /**
             * Recenttasktitles
             * @default []
             */
            recentTaskTitles: string[];
            /**
             * Stepsize
             * @default medium
             */
            stepSize: string;
            /**
             * Taskscompleted
             * @default 0
             */
            tasksCompleted: number;
            /**
             * Taskstotal
             * @default 0
             */
            tasksTotal: number;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Agentname */
            agentName: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Intent */
            intent: string;
            /** Mood */
            mood: string;
            /** Response */
            response: string;
        };
        /** DayOut */
        DayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Focusminutes */
            focusMinutes: number;
            /** Steps */
            steps: number;
            /** Tasks */
            tasks: number;
        };
        /** DecomposeRequest */
        DecomposeRequest: {
            /**
             * Stepsize
             * @default medium
             */
            stepSize: string;
            /** Tasktitle */
            taskTitle: string;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** DecomposeResponse */
        DecomposeResponse: {
            /** Steps */
            steps: components["schemas"]["StepResult"][];
            /**
             * Title
             * @default
             */
            title: string;
            /** Whyexplanation */
            whyExplanation: string;
        };
        /** ExtractedTask */
        ExtractedTask: {
            /** Tag */
            tag: string;
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** FocusSession */
        FocusSession: {
            /** Minutes */
            minutes: number;
        };
        /** GroundednessResult */
        GroundednessResult: {
            /** Grounded */
            grounded: boolean;
            /** Ungroundedpercentage */
            ungroundedPercentage: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportRequest
         * @description What the browser kept before sign-in (roadmap 4.5).
         */
        ImportRequest: {
            /** Activity */
            activity?: components["schemas"]["ImportedActivityEntry"][];
            preferences?: components["schemas"]["PreferencesUpdate"] | null;
            /** Tasks */
            tasks?: components["schemas"]["TaskCreate"][];
        };
        /** ImportResponse */
        ImportResponse: {
            /** Activity */
            activity: number;
            /** Preferences */
            preferences: boolean;
            /** Tasks */
            tasks: number;
        };
        /** ImportedActivityEntry */
        ImportedActivityEntry: {
            /** Action */
            action: string;
            agent: components["schemas"]["AgentName"];
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** @default passed */
            safetyStatus: components["schemas"]["SafetyStatus"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** MotivateRequest */
        MotivateRequest: {
            /**
             * Personality
             * @default gentle
             */
            personality: string;
            /**
             * Recenttasktitles
             * @default []
             */
            recentTaskTitles: string[];
            /**
             * Taskscompleted
             * @default 0
             */
            tasksCompleted: number;
            /**
             * Taskstotal
             * @default 0
             */
            tasksTotal: number;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** MotivateResponse */
        MotivateResponse: {
            /** Message */
            message: string;
            /** Mood */
            mood: string;
        };
        /** ParsedDocumentResponse */
        ParsedDocumentResponse: {
            /** Pages */
            pages: number;
            /** Text */
            text: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * PebbleColor
         * @enum {string}
         */
        PebbleColor: "lavender" | "sage" | "coral" | "amber" | "sky";
        /**
         * PebbleModel
         * @enum {string}
         */
        PebbleModel: "classic" | "chonky" | "mochi" | "minimal" | "chonky-plus" | "mochi-plus" | "minimal-plus";
        /**
         * PebblePersonality
         * @enum {string}
         */
        PebblePersonality: "gentle" | "playful" | "calm";
        /** PreferencesOut */
        PreferencesOut: {
            /** Calmmode */
            calmMode: boolean;
            pebbleColor: components["schemas"]["PebbleColor"];
            pebbleModel: components["schemas"]["PebbleModel"];
            pebblePersonality: components["schemas"]["PebblePersonality"];
            /** Readinglevel */
            readingLevel: number;
            /** Reduceanimations */
            reduceAnimations: boolean;
            stepSize: components["schemas"]["StepSize"];
        };
        /**
         * PreferencesUpdate
         * @description Only the fields sent are changed.
         */
        PreferencesUpdate: {
            /** Calmmode */
            calmMode?: boolean | null;
            pebbleColor?: components["schemas"]["PebbleColor"] | null;
            pebbleModel?: components["schemas"]["PebbleModel"] | null;
            pebblePersonality?: components["schemas"]["PebblePersonality"] | null;
            /** Readinglevel */
            readingLevel?: number | null;
            /** Reduceanimations */
            reduceAnimations?: boolean | null;
            stepSize?: components["schemas"]["StepSize"] | null;
        };
        /** ReaderTokenResponse */
        ReaderTokenResponse: {
            /** Subdomain */
            subdomain: string;
            /** Token */
            token: string;
        };
        /**
         * SafetyStatus
         * @enum {string}
         */
        SafetyStatus: "passed" | "flagged";
        /** SimplifyRequest */
        SimplifyRequest: {
            /**
             * Readinglevel
             * @default 5
             */
            readingLevel: number;
            /** Text */
            text: string;
        };
        /** SimplifyResponse */
        SimplifyResponse: {
            /** Extractedtasks */
            extractedTasks: components["schemas"]["ExtractedTask"][];
            groundedness: components["schemas"]["GroundednessResult"];
            /** Simplified */
            simplified: string;
            /** Tags */
            tags: string[];
            /** Whyexplanation */
            whyExplanation: string;
        };
        /** StatsOut */
        StatsOut: {
            allTime: components["schemas"]["TotalsOut"];
            byTag: components["schemas"]["ByTagOut"];
            /** Days */
            days: components["schemas"]["DayOut"][];
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            totals: components["schemas"]["TotalsOut"];
        };
        /** StepIn */
        StepIn: {
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /**
             * Timeestimate
             * @default
             */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** StepOut */
        StepOut: {
            /** Completed */
            completed: boolean;
            /** Id */
            id: string;
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** StepResult */
        StepResult: {
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /**
         * StepSize
         * @enum {string}
         */
        StepSize: "small" | "medium" | "large";
        /** StepUpdate */
        StepUpdate: {
            /** Completed */
            completed: boolean;
        };
        /** StepsReplace */
        StepsReplace: {
            /** Steps */
            steps: components["schemas"]["StepIn"][];
        };
        /** TaskCreate */
        TaskCreate: {
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
            /** Steps */
            steps?: components["schemas"]["StepIn"][];
            /** @default project */
            tag: components["schemas"]["TaskTag"];
            /**
             * Timeestimate
             * @default
             */
            timeEstimate: string;
            /** Title */
            title: string;
            /**
             * Whyexplanation
             * @default
             */
            whyExplanation: string;
        };
        /** TaskOut */
        TaskOut: {
            /** Completed */
            completed: boolean;
            /** Id */
            id: string;
            priority: components["schemas"]["TaskPriority"];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            tag: components["schemas"]["TaskTag"];
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
            /** Whyexplanation */
            whyExplanation: string;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "high" | "medium" | "low";
        /**
         * TaskTag
         * @enum {string}
         */
        TaskTag: "study" | "communication" | "project" | "wellbeing";
        /**
         * TaskUpdate
         * @description Only the fields sent are changed.
         */
        TaskUpdate: {
            /** Completed */
            completed?: boolean | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            tag?: components["schemas"]["TaskTag"] | null;
            /** Timeestimate */
            timeEstimate?: string | null;
            /** Title */
            title?: string | null;
            /** Whyexplanation */
            whyExplanation?: string | null;
        };
        /**
         * TasksOrder
         * @description Every task on the list, in the new order.
         */
        TasksOrder: {
            /** Taskids */
            taskIds: string[];
        };
        /** TotalsOut */
        TotalsOut: {
            /** Focusminutes */
            focusMinutes: number;
            /** Steps */
            steps: number;
            /** Tasks */
            tasks: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_account_api_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_account_data_api_account_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_activity_api_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_agents_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Pebble's response with detected intent, agent used, and optional structured data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decompose_api_agents_decompose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecomposeRequest"];
            };
        };
        responses: {
            /** @description Time-boxed steps with an explanation of why they were split this way */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecomposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    motivate_api_agents_motivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotivateRequest"];
            };
        };
        responses: {
            /** @description A personalized motivational message and suggested Pebble mood */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotivateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simplify_api_agents_simplify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimplifyRequest"];
            };
        };
        responses: {
            /** @description Simplified text, extracted tags, action items, and explanation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimplifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    immersive_reader_token_api_documents_immersive_reader_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderTokenResponse"];
                };
            };
        };
    };
    parse_api_documents_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_api_documents_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_local_data_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences__api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    update_preferences_api_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: {
                /** @description How many days, up to and including today */
                days?: number;
                /** @description Your time zone, e.g. Europe/Berlin */
                tz?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_focus_session_api_stats_focus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FocusSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
        };
    };
    add_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_tasks_api_tasks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reorder_tasks_api_tasks_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TasksOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    break_down_api_tasks__task_id__breakdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreakdownRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_breakdown_api_tasks__task_id__breakdown_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_steps_api_tasks__task_id__steps_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepsReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_step_api_tasks__task_id__steps__step_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
