/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with Pebble
         * @description **Pebble Orchestrator** — The main entry point for talking to Pebble.
         *
         *     Classifies the user's intent and routes to the appropriate sub-agent:
         *     - `decompose` → CalmSense (task breakdown)
         *     - `simplify` → SimplifyCore (text simplification)
         *     - `motivate` → PebbleVoice (encouragement)
         *     - `chat` → Direct response from Pebble
         *     - `distress` → Immediate empathetic response with support
         *
         *     All input is screened by Prompt Shields (anti-jailbreak) and Content Safety, then PII-redacted:
         *     the classifier and every sub-agent see only the redacted message. A flagged reply is replaced
         *     with a safe one.
         *
         *     If the user expresses distress (*"I'm overwhelmed"*, *"I can't do this"*),
         *     Pebble responds with empathy and offers to simplify their day.
         *
         *     The `data` field contains structured output from the sub-agent (e.g., subtasks
         *     for decompose, simplified text for simplify), or `null` for chat/distress.
         */
        post: operations["chat_api_agents_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/decompose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Break down a task
         * @description **Agent: CalmSense** — Takes a task title and breaks it into smaller, achievable subtasks.
         *
         *     Respects the user's preferred chunk size:
         *     - `small`: 5-10 minute steps
         *     - `medium`: 15-20 minute steps
         *     - `large`: 30+ minute steps
         *
         *     The agent starts with the easiest step to reduce task initiation friction,
         *     and includes a `whyExplanation` describing why it chose this breakdown.
         *
         *     Input and output go through the safety gate (Content Safety and PII redaction).
         */
        post: operations["decompose_api_agents_decompose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/motivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get encouragement
         * @description **Agent: PebbleVoice** — Generates specific, personalized encouragement.
         *
         *     Never generic platitudes. The agent references the user's actual progress:
         *     - *"You finished reading that chapter even though you said it felt hard"*
         *     - *"Starting is the hardest part, and you did that"*
         *
         *     Returns a `mood` that the frontend uses to update Pebble's expression:
         *     `sleepy`, `normal`, `happy`, or `excited`.
         */
        post: operations["motivate_api_agents_motivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/simplify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simplify text
         * @description **Agent: SimplifyCore** — Simplifies complex text to a target reading level (1-10).
         *
         *     Reading level scale:
         *     - **1-3**: Very short sentences, common words only
         *     - **4-6**: Clear language, some compound sentences
         *     - **7-9**: Closer to original, simplified structure
         *     - **10**: Minimal changes, just improved clarity
         *
         *     Also extracts action items (`extractedTasks`) and topic tags from the text.
         *     Includes a `whyExplanation` describing what was changed and why.
         *     Output is verified against the original text using Groundedness Detection.
         */
        post: operations["simplify_api_agents_simplify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/immersive-reader/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an Immersive Reader token
         * @description A short-lived token for Microsoft's Immersive Reader, used by the frontend's `launchAsync`.
         *
         *     Optional: without `IMMERSIVE_READER_*` settings this is a 503, and the frontend uses its built-in reader.
         */
        get: operations["immersive_reader_token_api_documents_immersive_reader_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read a document's text
         * @description Read the text of an uploaded document with a local parser (pypdf, python-docx).
         *
         *     The file is parsed in memory and **never stored**: nothing is written to disk or sent to
         *     another service. Pass the returned `text` to `POST /api/agents/simplify` to simplify it.
         */
        post: operations["parse_api_documents_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if the server is running.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your tasks
         * @description Your tasks in the order you added them, each with its steps (`subtasks`).
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /**
         * Add a task
         * @description Add a task to the end of your list. Pebble picks the ids of the task and its steps.
         */
        post: operations["add_task_api_tasks_post"];
        /**
         * Clear your list
         * @description Remove every task on your list.
         */
        delete: operations["clear_tasks_api_tasks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a task */
        delete: operations["delete_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /**
         * Change a task
         * @description Change only the fields you send, for example `{"completed": true}`.
         */
        patch: operations["update_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a task's steps
         * @description Set a task's steps, for example from a CalmSense breakdown. The new steps start open.
         */
        put: operations["replace_subtasks_api_tasks__task_id__subtasks_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/subtasks/{subtask_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Tick a step on or off
         * @description Finishing the last open step also finishes the task. Unticking a step never reopens it.
         */
        patch: operations["update_subtask_api_tasks__task_id__subtasks__subtask_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_parse_api_documents_parse_post */
        Body_parse_api_documents_parse_post: {
            /**
             * File
             * @description PDF, Word (.docx) or plain-text file. Max 10 MB.
             */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Chunksize
             * @default medium
             */
            chunkSize: string;
            /** Message */
            message: string;
            /**
             * Personality
             * @default gentle
             */
            personality: string;
            /**
             * Readinglevel
             * @default 5
             */
            readingLevel: number;
            /**
             * Recenttasktitles
             * @default []
             */
            recentTaskTitles: string[];
            /**
             * Taskscompleted
             * @default 0
             */
            tasksCompleted: number;
            /**
             * Taskstotal
             * @default 0
             */
            tasksTotal: number;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Agentname */
            agentName: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Intent */
            intent: string;
            /** Mood */
            mood: string;
            /** Response */
            response: string;
        };
        /** DecomposeRequest */
        DecomposeRequest: {
            /**
             * Chunksize
             * @default medium
             */
            chunkSize: string;
            /** Tasktitle */
            taskTitle: string;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** DecomposeResponse */
        DecomposeResponse: {
            /** Subtasks */
            subtasks: components["schemas"]["SubtaskResult"][];
            /** Whyexplanation */
            whyExplanation: string;
        };
        /** ExtractedTask */
        ExtractedTask: {
            /** Tag */
            tag: string;
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** GroundednessResult */
        GroundednessResult: {
            /** Grounded */
            grounded: boolean;
            /** Ungroundedpercentage */
            ungroundedPercentage: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MotivateRequest */
        MotivateRequest: {
            /**
             * Personality
             * @default gentle
             */
            personality: string;
            /**
             * Recenttasktitles
             * @default []
             */
            recentTaskTitles: string[];
            /**
             * Taskscompleted
             * @default 0
             */
            tasksCompleted: number;
            /**
             * Taskstotal
             * @default 0
             */
            tasksTotal: number;
            /**
             * Timeofday
             * @default day
             */
            timeOfDay: string;
        };
        /** MotivateResponse */
        MotivateResponse: {
            /** Message */
            message: string;
            /** Mood */
            mood: string;
        };
        /** ParsedDocumentResponse */
        ParsedDocumentResponse: {
            /** Pages */
            pages: number;
            /** Text */
            text: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** ReaderTokenResponse */
        ReaderTokenResponse: {
            /** Subdomain */
            subdomain: string;
            /** Token */
            token: string;
        };
        /** SimplifyRequest */
        SimplifyRequest: {
            /**
             * Readinglevel
             * @default 5
             */
            readingLevel: number;
            /** Text */
            text: string;
        };
        /** SimplifyResponse */
        SimplifyResponse: {
            /** Extractedtasks */
            extractedTasks: components["schemas"]["ExtractedTask"][];
            groundedness: components["schemas"]["GroundednessResult"];
            /** Simplified */
            simplified: string;
            /** Tags */
            tags: string[];
            /** Whyexplanation */
            whyExplanation: string;
        };
        /** SubtaskIn */
        SubtaskIn: {
            /**
             * Timeestimate
             * @default
             */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** SubtaskOut */
        SubtaskOut: {
            /** Completed */
            completed: boolean;
            /** Id */
            id: string;
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** SubtaskResult */
        SubtaskResult: {
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
        };
        /** SubtaskUpdate */
        SubtaskUpdate: {
            /** Completed */
            completed: boolean;
        };
        /** SubtasksReplace */
        SubtasksReplace: {
            /** Subtasks */
            subtasks: components["schemas"]["SubtaskIn"][];
        };
        /** TaskCreate */
        TaskCreate: {
            /**
             * Completed
             * @default false
             */
            completed: boolean;
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
            /** Subtasks */
            subtasks?: components["schemas"]["SubtaskIn"][];
            /** @default project */
            tag: components["schemas"]["TaskTag"];
            /**
             * Timeestimate
             * @default
             */
            timeEstimate: string;
            /** Title */
            title: string;
            /**
             * Whyexplanation
             * @default
             */
            whyExplanation: string;
        };
        /** TaskOut */
        TaskOut: {
            /** Completed */
            completed: boolean;
            /** Id */
            id: string;
            priority: components["schemas"]["TaskPriority"];
            /** Subtasks */
            subtasks: components["schemas"]["SubtaskOut"][];
            tag: components["schemas"]["TaskTag"];
            /** Timeestimate */
            timeEstimate: string;
            /** Title */
            title: string;
            /** Whyexplanation */
            whyExplanation: string;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "high" | "medium" | "low";
        /**
         * TaskTag
         * @enum {string}
         */
        TaskTag: "study" | "communication" | "project" | "wellbeing";
        /**
         * TaskUpdate
         * @description Only the fields sent are changed.
         */
        TaskUpdate: {
            /** Completed */
            completed?: boolean | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            tag?: components["schemas"]["TaskTag"] | null;
            /** Timeestimate */
            timeEstimate?: string | null;
            /** Title */
            title?: string | null;
            /** Whyexplanation */
            whyExplanation?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_api_agents_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Pebble's response with detected intent, agent used, and optional structured data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decompose_api_agents_decompose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecomposeRequest"];
            };
        };
        responses: {
            /** @description Time-boxed subtasks with an explanation of why they were split this way */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecomposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    motivate_api_agents_motivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotivateRequest"];
            };
        };
        responses: {
            /** @description A personalized motivational message and suggested Pebble mood */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotivateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simplify_api_agents_simplify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimplifyRequest"];
            };
        };
        responses: {
            /** @description Simplified text, extracted tags, action items, and explanation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimplifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    immersive_reader_token_api_documents_immersive_reader_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderTokenResponse"];
                };
            };
        };
    };
    parse_api_documents_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_api_documents_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
        };
    };
    add_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_tasks_api_tasks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_subtasks_api_tasks__task_id__subtasks_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtasksReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subtask_api_tasks__task_id__subtasks__subtask_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                subtask_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
